# Generated by Django 6.1.1 on 2026-09-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Coordinación'), ('TUTOR', 'Tutor FFE'), ('ALUMNO', 'Alumnado'), ('EMPRESA', 'Empresa')], max_length=10),
        ),
    ]
