# Generated by Django 6.1.1 on 2026-09-23 17:14

import django.core.files.storage
import django.db.models.deletion
import pathlib
import practicas.models
import practicas.validadores
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True, validators=[practicas.validadores.validar_codigo_centro], verbose_name='código de centro')),
                ('nombre', models.CharField(max_length=160)),
                ('localidad', models.CharField(max_length=120)),
                ('provincia', models.CharField(blank=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=16, validators=[practicas.validadores.validar_telefono], verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'centro',
                'verbose_name_plural': 'centros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Por ejemplo: 2º DAW', max_length=120)),
                ('anio_inicio', models.PositiveSmallIntegerField(verbose_name='año de inicio')),
                ('anio_fin', models.PositiveSmallIntegerField(verbose_name='año de fin')),
                ('codigo_matricula', models.CharField(help_text='El alumnado lo usa para registrarse en este curso. Compártelo solo con tu grupo.', max_length=20, unique=True, verbose_name='código de autorregistro')),
                ('autorregistro', models.BooleanField(default=False, help_text='Si está desactivado, solo el tutor puede dar de alta alumnado.', verbose_name='autorregistro abierto')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='practicas.centro')),
            ],
            options={
                'ordering': ['-anio_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True, validators=[practicas.validadores.validar_dni_nie], verbose_name='DNI/NIE')),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=16, validators=[practicas.validadores.validar_telefono], verbose_name='teléfono')),
                ('cv', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/claude/fct/privado')), upload_to=practicas.models.ruta_cv, validators=[practicas.validadores.validar_pdf], verbose_name='currículum')),
                ('cv_actualizado', models.DateTimeField(blank=True, null=True)),
                ('alta', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='practicas.curso')),
            ],
            options={
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=9, unique=True, validators=[practicas.validadores.validar_cif], verbose_name='CIF/NIF')),
                ('nombre', models.CharField(max_length=160)),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('web', models.URLField(blank=True)),
                ('persona_contacto', models.CharField(max_length=160, verbose_name='persona de contacto')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=16, validators=[practicas.validadores.validar_telefono], verbose_name='teléfono')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(help_text='Por ejemplo: desarrollo backend', max_length=160)),
                ('plazas', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='INICIADO', max_length=10)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='inicio de las prácticas')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fin de las prácticas')),
                ('horas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='horas estipuladas')),
                ('jornada', models.CharField(blank=True, choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('PARTIDA', 'Partida'), ('FLEXIBLE', 'Flexible')], max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cerrado', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='practicas.curso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='practicas.empresa')),
            ],
            options={
                'verbose_name': 'proceso',
                'verbose_name_plural': 'procesos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ResponsableLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='nombre completo')),
                ('dni', models.CharField(max_length=9, validators=[practicas.validadores.validar_dni_nie], verbose_name='DNI/NIE')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_legal', to='practicas.empresa')),
            ],
            options={
                'verbose_name': 'responsable legal',
                'verbose_name_plural': 'responsables legales',
            },
        ),
        migrations.CreateModel(
            name='TutorFFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=16, validators=[practicas.validadores.validar_telefono], verbose_name='teléfono')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutores', to='practicas.centro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_ffe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tutor FFE',
                'verbose_name_plural': 'tutores FFE',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora')),
                ('medio', models.CharField(choices=[('TELEFONO', 'Teléfono'), ('EMAIL', 'Email'), ('VISITA', 'Visita'), ('ENTREVISTA', 'Entrevista con alumnado'), ('OTRO', 'Otro')], default='TELEFONO', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='practicas.empresa')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='practicas.proceso')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='practicas.tutorffe')),
            ],
            options={
                'verbose_name': 'seguimiento',
                'verbose_name_plural': 'seguimientos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='proceso',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='practicas.tutorffe', verbose_name='tutor responsable'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='practicas.tutorffe', verbose_name='tutor FFE'),
        ),
        migrations.CreateModel(
            name='TutorLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='nombre completo')),
                ('dni', models.CharField(max_length=9, validators=[practicas.validadores.validar_dni_nie], verbose_name='DNI/NIE')),
                ('telefono', models.CharField(max_length=16, validators=[practicas.validadores.validar_telefono], verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='practicas.empresa')),
            ],
            options={
                'verbose_name': 'tutor laboral',
                'verbose_name_plural': 'tutores laborales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='proceso',
            name='tutor_laboral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to='practicas.tutorlaboral', verbose_name='tutor laboral'),
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SELECCIONADO', 'Seleccionado'), ('DESCARTADO', 'No seleccionado'), ('RETIRADO', 'Retirado')], default='PENDIENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='inicio de las prácticas')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fin de las prácticas')),
                ('horas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='horas estipuladas')),
                ('jornada', models.CharField(blank=True, choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('PARTIDA', 'Partida'), ('FLEXIBLE', 'Flexible')], max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='practicas.alumno')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='practicas.proceso')),
            ],
            options={
                'verbose_name': 'participación',
                'verbose_name_plural': 'participaciones',
                'ordering': ['alumno__apellidos', 'alumno__nombre'],
                'constraints': [models.UniqueConstraint(fields=('proceso', 'alumno'), name='alumno_una_vez_por_proceso')],
            },
        ),
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='practicas.alumno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='practicas.empresa')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practicas.tutorffe')),
            ],
            options={
                'verbose_name': 'solicitud de contacto',
                'verbose_name_plural': 'solicitudes de contacto',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'alumno'), name='una_solicitud_por_alumno')],
            },
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('centro', 'nombre', 'anio_inicio'), name='curso_unico_por_promocion'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.CheckConstraint(condition=models.Q(('anio_fin__gte', models.F('anio_inicio'))), name='curso_anios_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='tutorlaboral',
            constraint=models.UniqueConstraint(fields=('empresa', 'dni'), name='tutor_unico_por_empresa'),
        ),
    ]
