# Generated by Django 6.1.1 on 2026-09-23 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='anonimizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='informado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se le informó del tratamiento de sus datos.', null=True, verbose_name='información de protección de datos aceptada'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='informada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='información de protección de datos aceptada'),
        ),
        migrations.CreateModel(
            name='AccesoCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=160)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_cv', to='practicas.alumno')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acceso a un CV',
                'verbose_name_plural': 'accesos a los CV',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('version_cv', models.CharField(blank=True, help_text='CV sobre el que se comentó.', max_length=64)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_cv', to='practicas.alumno')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_cv', to='practicas.tutorffe')),
            ],
            options={
                'verbose_name': 'comentario sobre el CV',
                'verbose_name_plural': 'comentarios sobre el CV',
                'ordering': ['-fecha'],
            },
        ),
    ]
