# Generated by Django 6.1.1 on 2026-09-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0002_alumno_anonimizado_alumno_informado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='disponibilidad',
            field=models.CharField(blank=True, help_text='Por ejemplo: tardes a partir de las 15:30; no puedo los viernes.', max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='horas_exentas',
            field=models.PositiveSmallIntegerField(default=0, help_text='Por experiencia laboral, exención parcial u horas ya realizadas.', verbose_name='horas exentas o convalidadas'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='horas_requeridas',
            field=models.PositiveSmallIntegerField(default=370, help_text='Varía según el ciclo y la situación del alumno.', verbose_name='horas de FFE que debe realizar'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='jornada_preferida',
            field=models.CharField(blank=True, choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('PARTIDA', 'Partida'), ('FLEXIBLE', 'Flexible')], max_length=10, verbose_name='jornada que puede hacer'),
        ),
        migrations.AddField(
            model_name='participacion',
            name='origen',
            field=models.CharField(choices=[('TUTOR', 'Propuesto por el tutor'), ('EMPRESA', 'Propuesto por la empresa')], default='TUTOR', max_length=8),
        ),
    ]
